[package]
name = "fool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glfw = "0.41"
luminance = "0.44"
luminance-derive = "0.9.0"
luminance-glfw = "0.16"
luminance-windowing = "0.10"


